global using NSubstitute;
global using Shouldly;
global using Xunit;
global using MediatR;
global using NSubstitute.ReturnsExtensions;
global using MovieFlow.Shared.Abstractions.Kernel;
global using MovieFlow.Shared.Abstractions.Contexts;
global using MovieFlow.Shared.Abstractions.Time;
global using Microsoft.AspNetCore.Identity;
global using MovieFlow.Shared.Abstractions.Auth;
global using System.IdentityModel.Tokens.Jwt;
global using static MovieFlow.Modules.Users.Tests.Unit.Extensions.Extensions;