global using Microsoft.EntityFrameworkCore;
global using MediatR;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using MovieFlow.Shared.Abstractions;
global using MovieFlow.Shared.Abstractions.Kernel;
global using MovieFlow.Shared.Abstractions.Time;
